# Grano Hyprlock configuration

source = ~/.config/grano/colors.conf

$font_family = JetBrainsMono Nerd Font
$wallpaper = ~/.config/grano/wallpapers/wallpaper.webp

background {
    monitor =
    path = $wallpaper
    blur_passes = 2
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

label {
    monitor =
    text = $TIME
    color = rgba(255,255,255,0.95)
    font_size = 90
    font_family = $font_family
    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:43200000] date +"%A, %d %B %Y"
    color = rgba(255,255,255,0.95)
    font_size = 25
    font_family = $font_family
    position = -30, -150
    halign = right
    valign = top
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $grano_border_active_start
    inner_color = rgba(56,66,72,0.95)
    font_color = rgba(204,238,255,0.95)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1
    check_color = $grano_border_active_start
    fail_color = rgba(255,0,0,1)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, 4.5%
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:60000] echo "Good $(date +%H | awk '{if ($1 < 12) print "Morning"; else if ($1 < 18) print "Afternoon"; else print "Evening"}'), ${USER}"
    color = rgba(255,255,255,0.95)
    font_size = 20
    font_family = $font_family
    position = 0, -16%
    halign = center
    valign = center
}
