# Grano Hypridle configuration

$lock_command = hyprlock -c ~/.config/grano/hyprlock.conf

general {
    lock_cmd = $lock_command
    unlock_cmd = true
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 600
    on-timeout = brightnessctl -s && brightnessctl set 1%
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 500
    on-timeout = systemctl suspend
}
