#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
config_home=${XDG_CONFIG_HOME:-$HOME/.config}
grano_config="$config_home/grano"
wallpaper=${1:-"$grano_config/wallpapers/wallpaper.webp"}
output=${2:-"$grano_config/colors.conf"}
wallbash_bin=${WALLBASH_BIN:-"$HOME/.local/lib/hyde/wallbash.sh"}

if [[ ! -f "$wallpaper" ]]; then
    printf 'Wallpaper not found: %s\n' "$wallpaper" >&2
    exit 1
fi
if [[ ! -x "$wallbash_bin" ]]; then
    printf 'Wallbash not found: %s\n' "$wallbash_bin" >&2
    exit 1
fi
if ! command -v magick >/dev/null 2>&1; then
    printf '%s\n' 'ImageMagick (magick) is required by Wallbash.' >&2
    exit 1
fi

mkdir -p "$(dirname "$output")"
tmp_dcol=$(mktemp)
rm -f "$tmp_dcol"
trap 'rm -f "$tmp_dcol" "$tmp_dcol.dcol"' EXIT
"$wallbash_bin" "$wallpaper" "$tmp_dcol" >/dev/null
tmp_dcol="$tmp_dcol.dcol"

color_from_dcol() {
    local name=$1
    local value
    value=$(sed -n "s/^${name}=\\\"\\([[:xdigit:]]\\{6\\}\\)\\\"$/\\1/p" "$tmp_dcol")
    if [[ -z "$value" ]]; then
        printf 'Missing Wallbash color: %s\n' "$name" >&2
        exit 1
    fi
    printf 'rgba(%d,%d,%d,1)' "0x${value:0:2}" "0x${value:2:2}" "0x${value:4:2}"
}

active_start=$(color_from_dcol dcol_pry4)
active_end=$(color_from_dcol dcol_4xa1)
inactive_start=$(color_from_dcol dcol_pry1)
inactive_end=$(color_from_dcol dcol_pry2)

cat > "$output" <<EOF
# Generated by Grano Wallbash integration.
# Do not edit manually; regenerate with scripts/generate-colors.sh.

\$grano_border_active_start = $active_start
\$grano_border_active_end = $active_end
\$grano_border_inactive_start = $inactive_start
\$grano_border_inactive_end = $inactive_end
EOF

printf '%s\n' "Generated Grano colors: $output"
