#!/usr/bin/env bash
set -euo pipefail

config_home=${XDG_CONFIG_HOME:-$HOME/.config}
grano_config="$config_home/grano"
wallpaper=${1:-"$grano_config/wallpapers/wallpaper.webp"}
output=${2:-"$grano_config/colors.conf"}
wallbash_bin=${WALLBASH_BIN:-"$HOME/.local/lib/hyde/wallbash.sh"}

[[ -f "$wallpaper" ]] || { printf 'Wallpaper not found: %s\n' "$wallpaper" >&2; exit 1; }
command -v magick >/dev/null 2>&1 || { printf '%s\n' 'ImageMagick is required.' >&2; exit 1; }

hex_to_rgba() {
    local value=$1
    printf 'rgba(%d,%d,%d,1)' "0x${value:0:2}" "0x${value:2:2}" "0x${value:4:2}"
}

background=''
active=''
inactive=''
text=''
border_active_start=''
border_active_end=''
border_inactive_start=''
border_inactive_end=''

tmp_dcol=""
if [[ -x "$wallbash_bin" ]]; then
    tmp_dcol=$(mktemp)
    rm -f "$tmp_dcol"
    trap 'rm -f "$tmp_dcol" "$tmp_dcol.dcol"' EXIT
    "$wallbash_bin" "$wallpaper" "$tmp_dcol" >/dev/null
    tmp_dcol="$tmp_dcol.dcol"
fi

if [[ -n "$tmp_dcol" && -s "$tmp_dcol" ]]; then
    get_dcol() { sed -n "s/^$1=\"\([[:xdigit:]]\{6\}\)\"$/\1/p" "$tmp_dcol"; }
    background="#$(get_dcol dcol_pry1)"
    active="#$(get_dcol dcol_4xa7)"
    inactive="#$(get_dcol dcol_2xa4)"
    text="#$(get_dcol dcol_txt1)"
    border_active_start=$(get_dcol dcol_pry4)
    border_active_end=$(get_dcol dcol_4xa1)
    border_inactive_start=$(get_dcol dcol_pry1)
    border_inactive_end=$(get_dcol dcol_pry2)
else
    hex=$(magick "$wallpaper" -resize 1x1 -colorspace sRGB -format '%[hex:p{0,0}]' info:)
    hex=${hex:0:6}
    [[ "$hex" =~ ^[[:xdigit:]]{6}$ ]] || { printf 'Could not read wallpaper color.\n' >&2; exit 1; }
    r=$((16#${hex:0:2})); g=$((16#${hex:2:2})); b=$((16#${hex:4:2}))
    rgb() { printf '#%02X%02X%02X' "$1" "$2" "$3"; }
    background=$(rgb $((r*55/100)) $((g*55/100)) $((b*55/100)))
    active=$(rgb $((r+(255-r)*55/100)) $((g+(255-g)*55/100)) $((b+(255-b)*55/100)))
    inactive=$(rgb $((r*75/100)) $((g*75/100)) $((b*75/100)))
    text=$(rgb $((r+(255-r)*90/100)) $((g+(255-g)*90/100)) $((b+(255-b)*90/100)))
    border_active_start=$(printf '%02X%02X%02X' $((r+(255-r)*55/100)) $((g+(255-g)*55/100)) $((b+(255-b)*55/100)))
    border_active_end=$(printf '%02X%02X%02X' $((r+(255-r)*75/100)) $((g+(255-g)*75/100)) $((b+(255-b)*75/100)))
    border_inactive_start=$(printf '%02X%02X%02X' $((r*35/100)) $((g*35/100)) $((b*35/100)))
    border_inactive_end=$(printf '%02X%02X%02X' $((r*55/100)) $((g*55/100)) $((b*55/100)))
fi

mkdir -p "$(dirname "$output")" "$grano_config/waybar" "$grano_config/kitty" "$grano_config/rofi"
cat > "$output" <<EOF
# Generated by Grano from the active wallpaper.
# Versioned fallback is stored in the repository.
\$grano_border_active_start = $(hex_to_rgba "$border_active_start")
\$grano_border_active_end = $(hex_to_rgba "$border_active_end")
\$grano_border_inactive_start = $(hex_to_rgba "$border_inactive_start")
\$grano_border_inactive_end = $(hex_to_rgba "$border_inactive_end")
EOF
cat > "$grano_config/waybar/theme.css" <<EOF
@define-color bar-bg ${background}f2;
@define-color main-bg $background;
@define-color main-fg $text;
@define-color active $active;
@define-color accent $active;
@define-color muted $inactive;
EOF
cat > "$grano_config/kitty/theme.conf" <<EOF
background $background
foreground $text
color0 $background
color8 $inactive
color1 #DD6777
color9 #E26C7C
color2 $inactive
color10 $active
color3 $active
color11 $active
color4 $active
color12 $active
color5 $inactive
color13 $active
color6 $active
color14 $active
color7 $text
color15 $text
cursor $text
cursor_text_color $background
selection_foreground $text
selection_background $inactive
EOF
cat > "$grano_config/rofi/theme.rasi" <<EOF
* {
    main-bg: ${background}e6;
    main-fg: ${text}ff;
    main-br: ${active}cc;
    main-ex: ${active}cc;
    select-bg: ${active}ff;
    select-fg: ${background}ff;
    separatorcolor: transparent;
    border-color: transparent;
}
EOF
printf '%s\n' "Generated Grano colors from $wallpaper"
