#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
config_home=${XDG_CONFIG_HOME:-$HOME/.config}
grano_config="$config_home/grano"
wallpaper=${1:-"$grano_config/wallpapers/wallpaper.webp"}
output=${2:-"$grano_config/colors.conf"}
wallbash_bin=${WALLBASH_BIN:-"$HOME/.local/lib/hyde/wallbash.sh"}
waybar_theme="$grano_config/waybar/theme.css"
kitty_theme="$grano_config/kitty/theme.conf"
rofi_theme="$grano_config/rofi/theme.rasi"

if [[ ! -f "$wallpaper" ]]; then
    printf 'Wallpaper not found: %s\n' "$wallpaper" >&2
    exit 1
fi
if [[ ! -x "$wallbash_bin" ]]; then
    printf 'Wallbash not found: %s\n' "$wallbash_bin" >&2
    exit 1
fi
if ! command -v magick >/dev/null 2>&1; then
    printf '%s\n' 'ImageMagick (magick) is required by Wallbash.' >&2
    exit 1
fi

mkdir -p "$(dirname "$output")"
tmp_dcol=$(mktemp)
rm -f "$tmp_dcol"
trap 'rm -f "$tmp_dcol" "$tmp_dcol.dcol"' EXIT
"$wallbash_bin" "$wallpaper" "$tmp_dcol" >/dev/null
tmp_dcol="$tmp_dcol.dcol"

color_from_dcol() {
    local name=$1
    local value
    value=$(sed -n "s/^${name}=\\\"\\([[:xdigit:]]\\{6\\}\\)\\\"$/\\1/p" "$tmp_dcol")
    if [[ -z "$value" ]]; then
        printf 'Missing Wallbash color: %s\n' "$name" >&2
        exit 1
    fi
    printf 'rgba(%d,%d,%d,1)' "0x${value:0:2}" "0x${value:2:2}" "0x${value:4:2}"
}

active_start=$(color_from_dcol dcol_pry4)
active_end=$(color_from_dcol dcol_4xa1)
inactive_start=$(color_from_dcol dcol_pry1)
inactive_end=$(color_from_dcol dcol_pry2)

hex_from_dcol() {
    local name=$1
    local value
    value=$(sed -n "s/^${name}=\"\([[:xdigit:]]\{6\}\)\"$/\1/p" "$tmp_dcol")
    if [[ -z "$value" ]]; then
        printf 'Missing Wallbash color: %s\n' "$name" >&2
        exit 1
    fi
    printf '#%s' "$value"
}

pry1=$(hex_from_dcol dcol_pry1)
pry2=$(hex_from_dcol dcol_pry2)
pry3=$(hex_from_dcol dcol_pry3)
pry4=$(hex_from_dcol dcol_pry4)
txt1=$(hex_from_dcol dcol_txt1)
txt4=$(hex_from_dcol dcol_txt4)
accent1=$(hex_from_dcol dcol_1xa7)
accent2=$(hex_from_dcol dcol_2xa7)
accent3=$(hex_from_dcol dcol_3xa7)
accent4=$(hex_from_dcol dcol_4xa7)
accent=$accent3

mkdir -p "$(dirname "$waybar_theme")" "$(dirname "$kitty_theme")" "$(dirname "$rofi_theme")"

cat > "$waybar_theme" <<EOF
@define-color bar-bg ${pry1}f2;
@define-color main-bg $pry1;
@define-color main-fg $txt1;
@define-color active $accent4;
@define-color accent $accent3;
@define-color muted $accent2;
EOF

cat > "$kitty_theme" <<EOF
# Generated by Grano Wallbash integration.
background $pry1
foreground $txt1
color0 $pry1
color8 $pry2
color1 #dd6777
color9 #e26c7c
color4 $accent4
color12 $accent3
color3 $accent
color11 $accent
color2 $accent2
color10 $accent2
color5 $accent1
color13 $accent1
color6 $accent2
color14 $accent2
color7 $txt1
color15 $txt1
cursor $txt1
cursor_text_color $pry1
selection_foreground $txt1
selection_background $pry2
EOF

cat > "$rofi_theme" <<EOF
/* Generated by Grano Wallbash integration. */
* {
    main-bg: ${pry1}e6;
    main-fg: ${txt1}ff;
    main-br: ${accent2}cc;
    main-ex: ${accent4}cc;
    select-bg: ${accent4}ff;
    select-fg: ${pry1}ff;
    separatorcolor: transparent;
    border-color: transparent;
}
EOF

cat > "$output" <<EOF
# Generated by Grano Wallbash integration.
# Do not edit manually; regenerate with scripts/generate-colors.sh.

\$grano_border_active_start = $active_start
\$grano_border_active_end = $active_end
\$grano_border_inactive_start = $inactive_start
\$grano_border_inactive_end = $inactive_end
EOF

printf '%s\n' "Generated Grano colors: $output"
printf '%s\n' "Generated Waybar, Kitty, and Rofi themes"
